### ISSUE TITLE
[TRACKER] rom-properties-1.2 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#102]
Here's the meta issue for rom-properties-1.2, the Dreamcast release.

- [ ] #79: cmake can't find NASM on Win 10
- [ ] #89: [win32] KeyManagerTab: Shrinking the "Valid?" tab causes the icon to be drawn out of bounds.
- [x] #91: Slight Change to NDS roms
- [x] #92: (Suggestion) Support for 3DS Badge Files (.prb and .cab)
- [x] #93: improper handling for several badges
- [x] #94: Use RpPngWriter for standalone thumbnailers.
- [x] #95: libpng: pnglibconf.dfa needs to be LF line endings.
- [ ] #96: +x mode is not set on rp-config
- [x] #97: RpPng: Set and/or load sBIT.
- [ ] #100: AboutTab: Add more stuff on KDE; implement on Windows.
- [x] #101: SegaPVR: Ignore "Pixel Format" for DXT1-encoded GCN images?
- [ ] #103: [win32] AboutTab: ROM chip icon looks ugly on Windows 7.
- [x] #106: iQue DS roms use *.ids file extension for some reason, add that
- [ ] #107: Dreamcast: CDI support.

**Comment by GerbilSoft** [comment]
Added #103: [win32] AboutTab: ROM chip icon looks ugly on Windows 7.

**Comment by GerbilSoft** [comment]
Added #106: iQue DS roms use *.ids file extension for some reason, add that

**Comment by GerbilSoft** [comment]
Added #107: Dreamcast: CDI support.

**Comment by GerbilSoft** [comment]
1.2 is out. Some of this stuff didn't get finished in time.
