### ISSUE TITLE
[TRACKER] rom-properties-1.3 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#123]
rom-properties 1.3, "The Internationalization Release"

- [x] #79: cmake can't find NASM on Win 10
- [x] #96: +x mode is not set on rp-config
- [x] #110: Use gettext for translations.
- [x] #111: Add support for Valve VTF format.
- [ ] #113: Support for Xbox One DDS files.
- [x] #117: Suggestion: Add support for WUX compression format Wii U disc images
- [ ] #119: Use templates instead of including 30 nearly-identical files in RomDataFactory
- [x] #121: [KDE, Win32] Key Manager shows an error icon when the key is empty, but present in keys.conf
- [x] #122: [win32] Build and link in GNU gettext or equivalent 
- [x] #126: Fedora: rp-stub has the wrong path for KDE5
- [x] #128: [win32] Properties tab doesn't show up for .dds if Visual Studio 2017 is installed
- [x] #129: gettext truncates Win32 file filters because of embedded nulls
- [ ] #132: translatability issues
- [x] #135: rpcli: CI8 BMP export may be unaligned.

**Comment by GerbilSoft** [comment]
Added #119.

**Comment by GerbilSoft** [comment]
Added #129.

**Comment by GerbilSoft** [comment]
Added #132.

**Comment by GerbilSoft** [comment]
Added #79.

**Comment by GerbilSoft** [comment]
Added #135.

**Comment by GerbilSoft** [comment]
Closed due to the release of 1.3.
