### ISSUE TITLE
[TRACKER] rom-properties-0.8 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#16]
The issue tracker is getting filled with issues for "later", so here's a meta-issue for everything blocking the first release, 0.8 "Beta 1".

- [x] #2: Implement PNG image loading in libromdata.
- [x] #3: Use pngcheck to verify downloaded PNG images.
- [x] #4: rp_image subclasses with factory class.
- [x] #7: Wii: Parse the update partition to get the system update version.
- [x] #9: Change ascii_to_rp_string() to latin1_to_rp_string(); use it for Nintendo DS titles.
- [x] #10: Use std::unique_ptr instead of std::auto_ptr.
- [x] #11: Detect specific system for Mega Drive ROMs.
- [x] #13: Implement IThumbnailProvider for proper alpha transparency on Windows Vista and later.
- [x] #14: Enable stack smashing protection by default.
- [x] #17: Write a test suite for GcnFst.
- [x] #20: Win32 property sheets don't work when a file extension has associations set.

All other enhancements should be postponed until 0.9 or later.

**Comment by GerbilSoft** [comment]
Added issue #17, which is fairly important because GcnFst is a bit hackish.

**Comment by GerbilSoft** [comment]
Added issue #20, which prevents the shell extension from working on Windows systems where the user already set a file association.

**Comment by GerbilSoft** [comment]
Removed #5 due to crashes in shell32.dll with IEIFLAG_ASYNC enabled. Windows XP usage is declining rapidly, so this won't affect too many users.

**Comment by GerbilSoft** [comment]
All blockers complete; now I just have to write some packaging scripts and build binary packages for Windows and Ubuntu 16.04. (14.04 doesn't have KDE5.)

**Comment by GerbilSoft** [comment]
v0.8 released today.
