### ISSUE TITLE
[TRACKER] rom-properties-0.8 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#16]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GerbilSoft](https://github.com/GerbilSoft)**
_Tuesday Sep 13, 2016 at 19:58 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/16_

----

The issue tracker is getting filled with issues for "later", so here's a meta-issue for everything blocking the first release, 0.8 "Beta 1".
- [x] #2: Implement PNG image loading in libromdata.
- [x] #3: Use pngcheck to verify downloaded PNG images.
- [x] #4: rp_image subclasses with factory class.
- [x] #7: Wii: Parse the update partition to get the system update version.
- [x] #9: Change ascii_to_rp_string() to latin1_to_rp_string(); use it for Nintendo DS titles.
- [x] #10: Use std::unique_ptr instead of std::auto_ptr.
- [x] #11: Detect specific system for Mega Drive ROMs.
- [x] #13: Implement IThumbnailProvider for proper alpha transparency on Windows Vista and later.
- [x] #14: Enable stack smashing protection by default.
- [x] #17: Write a test suite for GcnFst.
- [x] #20: Win32 property sheets don't work when a file extension has associations set.

All other enhancements should be postponed until 0.9 or later.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Friday Sep 16, 2016 at 19:26 GMT_

----

Added issue #17, which is fairly important because GcnFst is a bit hackish.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Tuesday Sep 27, 2016 at 18:51 GMT_

----

Added issue #20, which prevents the shell extension from working on Windows systems where the user already set a file association.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Saturday Oct 15, 2016 at 16:00 GMT_

----

Removed #5 due to crashes in shell32.dll with IEIFLAG_ASYNC enabled. Windows XP usage is declining rapidly, so this won't affect too many users.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Monday Oct 17, 2016 at 04:07 GMT_

----

All blockers complete; now I just have to write some packaging scripts and build binary packages for Windows and Ubuntu 16.04. (14.04 doesn't have KDE5.)

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Monday Oct 24, 2016 at 04:20 GMT_

----

v0.8 released today.
