### ISSUE TITLE
[TRACKER] rom-properties-1.4 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#169]
rom-properties 1.4, the "Audio and Metadata" release.

- [x] #19: GCN/Wii: Add support for more disc image formats.
- [x] #66: Limit rp-config, svrplus, etc. to single instance per user. enhancement
- [ ] #89: [win32] KeyManagerTab: Shrinking the "Valid?" tab causes the icon to be drawn out of bounds.
- [ ] #103: [win32] AboutTab: ROM chip icon looks ugly on Windows 7.
- [ ] #105: Windows: HiDPI support
- [x] #112: Display image properties for texture files. (KFileMetaData, IPropertyStore)
- [x] #116: Suggestion: Add support for the "internal" NES footer
- [x] #118: Add support for Wii WAD files
- [x] #125: GBX: footer for Game Boy ROMs
- [x] #134: String trimming stuff
- [x] #140: Use Cairo for GTK+ 3.x.
- [x] #143: New RFT_DIMENSIONS type for e.g. width/height/depth
- [x] #144: SparseDiscReader: Change readBlock() to getBlockStart() or similar.
- [ ] #145: [kde] rp-config: Thumbnail Cache tab
- [ ] #146: [win32] CacheTab: WinXP: Only use timer for media changes.
- [x] #147: Add a template for using std::unique_ptr<> with aligned malloc/free.
- [ ] #148: [win32] Disable the DLL if it's located in %SystemRoot%.
- [x] #149: [Linux] UI frontends: Return immediately if running as root.
- [x] #150: RomMetaData: Add a RomFields::STRF_TRIM_END equivalent.
- [ ] #151: In some edge cases, artwork doesn't download from GameTDB
- [ ] #152: Arch support?
- [x] #153: Game audio formats (VGM, etc)
- [x] #155: DLC WADs have no metadata shown
- [x] #156: [win32] Transparent gzip decompression for RP_ThumbnailProvider and RP_PropertyStore
- [x] #158: Windows 10 - Explorer crashes when loading multi-disc gamecube games
- [x] #159: Support mgd file format?
- [x] #164: Icon overlay for "dangerous" ROM permissions enhancement
- [x] #166: Make building with OpenGL optional.
- [x] #172: [win32] Vertically center RFT_LISTDATA icons.
- [ ] #173: [xfce] tumblerd is hanging waiting for rom-properties to thumbnail files.
- [x] #180: DDS: Parse NVTT headers.
- [x] #181: Incompatible with Caja
- [x] #183: iQue Player support
- [x] #185: MegaDrive: add .68k as an extension
- [x] #186: Update README.md (for iQue Player)

**Comment by GerbilSoft** [comment]
Added #172: [win32] Vertically center RFT_LISTDATA icons.

**Comment by GerbilSoft** [comment]
Added #173: [xfce] tumblerd is hanging waiting for rom-properties to thumbnail files.

**Comment by GerbilSoft** [comment]
Moved #127 and #131 to v1.5.

**Comment by GerbilSoft** [comment]
Added #181: Incompatible with Caja

**Comment by GerbilSoft** [comment]
Added #180: DDS: Parse NVTT headers.

**Comment by GerbilSoft** [comment]
Added #183: iQue Player support.

**Comment by GerbilSoft** [comment]
Added #185: MegaDrive: add .68k as an extension.

**Comment by GerbilSoft** [comment]
Added #186: Update README.md (for iQue Player)

**Comment by GerbilSoft** [comment]
Closed due to the release of 1.4.
