### ISSUE TITLE
[TRACKER] rom-properties-0.9 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#40]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GerbilSoft](https://github.com/GerbilSoft)**
_Sunday Jan 08, 2017 at 20:44 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/40_

----

Meta issue for 0.9. I'd like to get a release out sometime this month, so let's consolidate everything here.

- [ ] #5: Windows XP: Thumbnail downloads cause Explorer to freeze.
- [x] #8: Virtual Boy ROM Support
- [x] #18: Wii: Show "used size" for partitions.
- [x] #23: PlayStationSave: 16x16 icon shenanigans.
- [x] #24: [Suggestion] Support NES via iNES headers
- [x] #26: RomFields: Add age ratings type, and support DSi age ratings.
- [x] #27: IExtractIcon only uses icon from the first file in VC14 builds.
- [x] #28: ROM Properties tab uses mix of bitmapped and aliased fonts on Windows
- [x] #30: Include support for Mega Drive ROMs with .md extension
- [x] #32: Use libpng on all operating systems.
- [x] #33: amiibo bin support
- [ ] #34: IExtractIcon: Windows XP doesn't like non-square icons.
- [x] #35: Windows: Handle conflicting shell extensions for e.g. .bin
- [x] #36: Add APNG export; use numer/denom for icon delay.
- [ ] ~~#39: GTK+: Add thumbnailing support.~~

All other enhancements should be postponed until 1.0 or later.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Monday Jan 09, 2017 at 05:02 GMT_

----

#35 is fairly important. It's preventing us from registering for common types like .bin and conflicting types like .vb.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Tuesday Jan 24, 2017 at 04:26 GMT_

----

#39 is partially implemented (works on Nautilus). Retargetting for 1.0 due to Thunar needing more work (D-Bus service).

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Thursday Feb 02, 2017 at 03:05 GMT_

----

#28 is probably fixed. #5 and #34 will probably be delayed to 1.0.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Wednesday Feb 08, 2017 at 04:28 GMT_

----

v0.9-beta2 is out.
