### ISSUE TITLE
[TRACKER] rom-properties-1.0 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#59]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GerbilSoft](https://github.com/GerbilSoft)**
_Saturday May 06, 2017 at 21:24 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/59_

----

Here's the meta issue for the 1.0 release.

- [x] #34: IExtractIcon: Windows XP doesn't like non-square icons.
- [X] #41: Rework RomFields to use dynamic fields.
- [x] #47: Layout of Windows properties page off-center, age rating doesn't fit.
- [x] #50: Add support for multiple image sizes. (external images)
- [x] #52: [Windows] User configuration dialog for image types, etc.
- [X] #55: Support for S&K's KiS2 header data

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Saturday May 20, 2017 at 19:59 GMT_

----

And we're done here.

https://github.com/GerbilSoft/rom-properties/releases/tag/v1.0
