### ISSUE TITLE
[TRACKER] rom-properties-1.0 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#59]
Here's the meta issue for the 1.0 release.

- [x] #34: IExtractIcon: Windows XP doesn't like non-square icons.
- [X] #41: Rework RomFields to use dynamic fields.
- [x] #47: Layout of Windows properties page off-center, age rating doesn't fit.
- [x] #50: Add support for multiple image sizes. (external images)
- [x] #52: [Windows] User configuration dialog for image types, etc.
- [X] #55: Support for S&K's KiS2 header data

**Comment by GerbilSoft** [comment]
And we're done here.

https://github.com/GerbilSoft/rom-properties/releases/tag/v1.0
