### ISSUE TITLE
[TRACKER] rom-properties-1.1 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#77]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GerbilSoft](https://github.com/GerbilSoft)**
_Sunday Jun 11, 2017 at 00:31 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/77_

----

Here's the meta issue for the 1.1 release.

- [x] #39: GTK+: Add thumbnailing support.
- [ ] #43: Add ability to represent time with minute-precision
- [x] #44: NES: TNES extensions, submappers, other fields
- [ ] #51: EXE: Icon thumbnailing, and LX support.
- [x] #58: MegaDrive: Show the second ROM header for S&K lock-on
- [x] #60: Nintendo3DS: Show application permissions.
- [x] #62: [KDE] User configuration program
- [x] #63: RP_ShellPropSheetExt: Remove `iconAnimData` variable?
- [x] #64: Nintendo3DS: Support encrypted DSiWare CIAs.
- [ ] #65: NCCHReader: Report missing secondary keys correctly.
- [ ] #66: Limit rp-config, svrplus, etc. to single instance per user.
- [ ] #67: Add support for multiple image sizes. (internal images)
- [x] #68: rp-config: Add key editing and verification.
- [x] #72: [GTK+] Suspend animation when switching tabs.
- [x] #74: [win32] Use SetProcessMitigationPolicy on Win8+
- [x] #76: GTK+, KDE: Support RFT_LISTDATA rows_visible.
- [ ] #79: cmake can't find NASM on Win 10
- [x] #80: EXE: More info for MZ (PR #87)
- [x] #83: SJIS conversion failure
- [x] #85: Improve rpcli's png/zlib delayloading
- [x] #86: Added support for other PS1 save formats
- [x] #88: [win32] Disable LVS_EX_DOUBLEBUFFER in RDP sessions.

Some of these may be postponed to 1.2.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Sunday Jun 11, 2017 at 03:20 GMT_

----

Added #79, which prevents JPEG from being built on Windows because NASM can't be found in some cases.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Saturday Jun 17, 2017 at 16:11 GMT_

----

Added #83.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Sunday Jun 18, 2017 at 01:04 GMT_

----

Added #85 and #86.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Tuesday Jun 20, 2017 at 02:40 GMT_

----

Added #88.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Sunday Jun 25, 2017 at 17:04 GMT_

----

Added #80. (PR #87)

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Tuesday Jul 04, 2017 at 17:29 GMT_

----

Retargetting all unclosed issues to 1.2, but leaving them here for reference.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Thursday Jul 06, 2017 at 02:21 GMT_

----

Added #76, which was actually completed for 1.1.
