### ISSUE TITLE
[TRACKER] rom-properties-1.1 release

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#77]
Here's the meta issue for the 1.1 release.

- [x] #39: GTK+: Add thumbnailing support.
- [ ] #43: Add ability to represent time with minute-precision
- [x] #44: NES: TNES extensions, submappers, other fields
- [ ] #51: EXE: Icon thumbnailing, and LX support.
- [x] #58: MegaDrive: Show the second ROM header for S&K lock-on
- [x] #60: Nintendo3DS: Show application permissions.
- [x] #62: [KDE] User configuration program
- [x] #63: RP_ShellPropSheetExt: Remove `iconAnimData` variable?
- [x] #64: Nintendo3DS: Support encrypted DSiWare CIAs.
- [ ] #65: NCCHReader: Report missing secondary keys correctly.
- [ ] #66: Limit rp-config, svrplus, etc. to single instance per user.
- [ ] #67: Add support for multiple image sizes. (internal images)
- [x] #68: rp-config: Add key editing and verification.
- [x] #72: [GTK+] Suspend animation when switching tabs.
- [x] #74: [win32] Use SetProcessMitigationPolicy on Win8+
- [ ] #79: cmake can't find NASM on Win 10
- [x] #80: EXE: More info for MZ (PR #87)
- [x] #83: SJIS conversion failure
- [x] #85: Improve rpcli's png/zlib delayloading
- [x] #86: Added support for other PS1 save formats
- [x] #88: [win32] Disable LVS_EX_DOUBLEBUFFER in RDP sessions.

Some of these may be postponed to 1.2.

**Comment by GerbilSoft** [comment]
Added #79, which prevents JPEG from being built on Windows because NASM can't be found in some cases.

**Comment by GerbilSoft** [comment]
Added #83.

**Comment by GerbilSoft** [comment]
Added #85 and #86.

**Comment by GerbilSoft** [comment]
Added #88.

**Comment by GerbilSoft** [comment]
Added #80. (PR #87)

**Comment by GerbilSoft** [comment]
Retargetting all unclosed issues to 1.2, but leaving them here for reference.

**Comment by GerbilSoft** [comment]
Added #76, which was actually completed for 1.1.
